export default function WeeklyReport({ pos4to10, pos11to20, gaps, cannibalization }: any) {
    return (
        <div className="bg-gradient-to-br from-slate-900 to-slate-800 p-8 rounded-2xl border border-slate-700 shadow-xl text-white">
            <div className="flex items-center gap-3 mb-6 border-b border-slate-700 pb-4">
                <div className="w-10 h-10 bg-teal-500 rounded-lg flex items-center justify-center shadow-lg">
                    <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                    </svg>
                </div>
                <div>
                    <h2 className="text-2xl font-bold tracking-tight">Executive SEO Briefing</h2>
                    <p className="text-slate-400 text-sm font-medium">Auto-generated by AI Analysis</p>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="space-y-6">
                    <div>
                        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">What Changed?</h3>
                        <p className="text-sm text-slate-300">0 experiments deployed in the last 7 days.</p>
                    </div>
                    <div>
                        <h3 className="text-xs font-bold text-teal-400 uppercase tracking-wider mb-2">What is Growing?</h3>
                        <p className="text-sm text-slate-300">Analysis pending sufficient historical data (7 days required).</p>
                    </div>
                    <div>
                        <h3 className="text-xs font-bold text-red-400 uppercase tracking-wider mb-2">What is Declining?</h3>
                        <p className="text-sm text-slate-300">Analysis pending sufficient historical data (7 days required).</p>
                    </div>
                    <div>
                        <h3 className="text-xs font-bold text-amber-400 uppercase tracking-wider mb-2">What Should We Stop?</h3>
                        <p className="text-sm text-slate-300">
                            {cannibalization.length > 0 ? `${cannibalization.length} cannibalization conflicts detected. Stop creating redundant pages for ${cannibalization[0]?.query}.` : 'No destructive cannibalization detected.'}
                        </p>
                    </div>
                </div>

                <div className="space-y-6">
                    <div>
                        <h3 className="text-xs font-bold text-blue-400 uppercase tracking-wider mb-2">What Should We Fix?</h3>
                        <ul className="text-sm text-slate-300 space-y-2 list-disc list-inside">
                            {pos4to10.slice(0,2).map((opp: any, i: number) => (
                                <li key={i}>Update Title/H1 for <strong>"{opp.query}"</strong> (Currently pos {opp.position?.toFixed(1)})</li>
                            ))}
                            {pos4to10.length === 0 && <li>No immediate fixes required in Top 10.</li>}
                        </ul>
                    </div>
                    <div>
                        <h3 className="text-xs font-bold text-purple-400 uppercase tracking-wider mb-2">What Should We Build?</h3>
                        <ul className="text-sm text-slate-300 space-y-2 list-disc list-inside">
                            {gaps.slice(0,2).map((opp: any, i: number) => (
                                <li key={i}>Missing page for <strong>"{opp.query}"</strong> ({opp.impressions} lost impressions)</li>
                            ))}
                            {gaps.length === 0 && <li>No high-priority content gaps detected.</li>}
                        </ul>
                    </div>
                    <div className="bg-slate-800/50 p-4 rounded-lg border border-slate-700">
                        <h3 className="text-xs font-bold text-green-400 uppercase tracking-wider mb-2">Patient Enquiry Potential</h3>
                        <p className="text-sm text-slate-300">
                            <strong>{pos11to20.length}</strong> pages sitting on Page 2 (Pos 11-20) have "High" or "Very High" commercial intent. Pushing these to Page 1 via internal linking could generate direct patient leads.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
